name: Build Technical Architecture Document

on:
  push:
    paths:
      - 'TAD.md'
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate PDF
        uses: docker://pandoc/extra:3.7
        with:
          args: >
            TAD.md -o TAD.pdf
            --template=eisvogel
            --pdf-engine=xelatex
            --listings
            --number-sections
      

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Technical-Architecture-Document
          path: TAD.pdf
